export const DEFAULT_SUBAGENT_MAX_TURNS = 25;
export const SUBAGENT_RECURSION_MULTIPLIER = 3;
export const MAX_GRAPH_SUBAGENT_MEMBERS = 32;
export const MAX_GRAPH_SUBAGENT_TURNS = Math.floor(
  Number.MAX_SAFE_INTEGER /
    (SUBAGENT_RECURSION_MULTIPLIER * MAX_GRAPH_SUBAGENT_MEMBERS)
);
