name: CI

on:
  pull_request:
    branches:
      - dev
      - main
    paths-ignore:
      - '**.md'

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  validate:
    uses: ./.github/workflows/validate.yml
    secrets: inherit
